# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
# File Options
files:
  ignore:
    - 'consumables/scss/global/reset/*.scss'
    - 'consumables/scss/global/typography/font-face.scss'
    - 'consumables/scss/global/typography/_extends.scss'
# Rule Configuration
rules:
  # Extends and Mixins
  extends-before-mixins: 1
  extends-before-declarations: 1
  placeholder-in-extend: 1
  mixins-before-declarations: 1
  # Spaces and Lines
  one-declaration-per-line: 1
  final-newline: 1
  indentation: 1
  space-before-brace: 1
  space-after-comma: 1
  space-around-operator: 1
  empty-line-between-blocks:
    - 1
    - include: true
    - allow-single-line-rulesets: true
  # Other
  leading-zero: 1
  trailing-semicolon: 1
  quotes:
    - 1
    - style: single
  # Not Allowed
  no-color-keywords: 2
  no-misspelled-properties: 2
  no-ids: 2
  no-important: 2
  no-empty-rulesets: 2
  no-duplicate-properties: 1
  # Units
  property-units:
    - global: ['em']
    - per-property: { font-size: ['rem'] }
